### ISSUE TITLE
Handling duplicates?

### ISSUE THREAD

**Issue by weholt** [ramonsaraiva/pictory#1] opened 2018-10-10 06:37 UTC
Like this project, but it does not seem to handle duplicates.

**Comment by ramonsaraiva** [comment] 2018-10-11 12:51
Hello, unfortunately, not yet.
I'll probably implement some duplicates/collision strategy for the files, like the possibility to either override them or duplicate them with a specific prefix/suffix.

What do you think?

**Comment by weholt** [comment] 2018-10-12 06:30
I wrote a similar solution some years ago before using Lightroom for all my photo organization. The project is now retired, but it had a section looking like this (sorry for the bad formatting):

`default_duplicate_filename_format = '%(filename)s~%(counter)s%(file_extension)s'

def generate_valid_target(filename, duplicate_filename_format=default_duplicate_filename_format):
    """Generates a new filename if there is already an existing file with the same name.

    :param filename: the target file we want to create
    :returns: string
    """
    counter = 1
    while True:
        if not os.path.exists(filename):
            break
        base_name, ext = os.path.splitext(filename)
        filename = duplicate_filename_format % dict(filename=base_name, counter=counter, file_extension=ext)
        counter += 1
    return filename`

**Comment by ramonsaraiva** [comment] 2018-10-13 23:54
Adding the Hacktoberfest label in case someone wants to work on it.

**Comment by Abelarm** [comment] 2018-10-15 16:38
I'd like to work on this but i don't get exactly the problem neither the expected behaviour.

**Comment by ramonsaraiva** [comment] 2018-10-15 17:12
@Abelarm right now the program halts if there are duplicates (files with the exact same name), we need to have different options to handle those..

I think the steps here would be to add a proper arguments parser, giving different options for file collisions, like:

- overwriting
- adding a prefix/suffix to the dupes
- skipping

No need for something complex, just a simple handling of duplicates.

**Comment by Abelarm** [comment] 2018-10-15 18:09
This makes perfect sense to me :)

**Comment by ramonsaraiva** [comment] 2018-10-22 19:11
Fixed on https://github.com/ramonsaraiva/pictory/pull/5

**Closed as completed by ramonsaraiva** 2018-10-22 19:11 UTC
Labels: Hacktoberfest
